numpy is faster than list---Fixed type && Contagious memory---Learn SIMD Vector Processing because it is a benefit of numpy
Numpy does more  functios than list

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3],dtype='int16')

print(a)

[1 2 3]


In [ ]:
b = np.array([[4,5,6],[9,10.07,11.0]])
print(b)

[[ 4.    5.    6.  ]
 [ 9.   10.07 11.  ]]


In [ ]:
#Get the dimension
a.ndim


1

In [ ]:
b.ndim

2

In [ ]:
#Get shape
a.shape

(3,)

In [ ]:
b.shape

(2, 3)

In [ ]:
#Get the type
a.dtype

dtype('int16')

In [ ]:
# Get Size
a.itemsize

2

In [ ]:
# Get total size
a.size * a.itemsize

6

In [ ]:
b.size * b.itemsize

48

In [ ]:
b.itemsize

8

In [ ]:
b.dtype

dtype('float64')

In [ ]:
b.nbytes

48

In [ ]:
import numpy as np

# Create a 2D array with 2 rows and 7 elements per row
# You can change the number of rows (e.g., 3, 4, etc.) as desired
c = np.array([
    [1, 2, 3, 4, 5, 6, 7],
    [8, 9, 10, 11, 12, 13, 14]
])


In [ ]:
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
c.dtype

dtype('int64')

In [ ]:
c.shape

(2, 7)

In [ ]:
c.size

14

In [ ]:
#Get a specific element [r,c]
# Example I wanna have 13 here
c[1,5]

np.int64(13)

In [ ]:
#Now I want a number 4
c[0,3]

np.int64(4)

In [ ]:
#Taking negative element
c[1,-2]

np.int64(13)

In [ ]:
#Get a specific row
c[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
c[:1]

array([[1, 2, 3, 4, 5, 6, 7]])

In [ ]:
#Get a specific column
c[:,2]

array([ 3, 10])

In [ ]:
c[:,5]

array([ 6, 13])

In [ ]:
#Getting little bit more fancy [startindex : endindex : stepsize]
c[1, 2:7:2]

array([10, 12, 14])

In [ ]:
c[:,::3]

array([[ 1,  4,  7],
       [ 8, 11, 14]])

In [ ]:
#changing the value in the matrix
c[:,-1]=(2*c[:,-1])

In [ ]:
print(c)

[[ 1  2  3  4  5  6 14]
 [ 8  9 10 11 12 13 28]]


In [ ]:


# Create a 3D array
# This array has 2 'layers' (matrices)
# Each layer has 2 rows
# Each row has 3 elements
d = np.array([
    [ # First layer
        [1, 2, 3],
        [4, 5, 6]
    ],
    [ # Second layer
        [7, 8, 9],
        [10, 11, 12]
    ]
])

print(d)
print(f"Shape of array d: {d.shape}") # Should output (2, 2, 3)
print(f"Number of dimensions: {d.ndim}")

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape of array d: (2, 2, 3)
Number of dimensions: 3


In [ ]:
d.shape

(2, 2, 3)

In [ ]:
#Lets say i want 11
d[0,1,2]


np.int64(6)

In [ ]:
d[:,:,::2]

array([[[ 1,  3],
        [ 4,  6]],

       [[ 7,  9],
        [10, 12]]])

Initializing Different Types Of Arrays

In [ ]:
#All zeroes arrays
e=np.zeros((5,3,2))

In [ ]:
e.shape

(5, 3, 2)

In [ ]:
#All 1s matrix
np.ones((3,5,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
# Any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [ ]:
#Any other number (full_like)
np.full_like(e,4)

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [ ]:
# Random decimal number
np.random.rand(4,2)

array([[0.94013114, 0.0224218 ],
       [0.14276523, 0.95172944],
       [0.23464658, 0.70649514],
       [0.9284106 , 0.64337857]])

In [ ]:
#Random integers value
np.random.randint(0,10,size=(4,4))

array([[5, 6, 5, 0],
       [5, 8, 6, 4],
       [6, 1, 3, 8],
       [1, 9, 2, 5]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

We Need to initialize an 5*5 matrix with a 1 on the borders and o in the inner concentric border and 9 in the middle  

In [ ]:
f = np.ones((5,5))
print(f)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
u = np.zeros((3,3))
print(u)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
u[1,1]=9
print(u)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [ ]:
f[1:-1,1:-1] = u

In [ ]:
print(f)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Be Careful when copying arrays

In [ ]:
a = np.array([1,2,3])
b = a.copy()

In [ ]:
print(b)

[1 2 3]


In [ ]:
b[0]=100

In [ ]:
a

array([1, 2, 3])

In [ ]:
b

array([100,   2,   3])

MATHEMATICS

In [ ]:
a =np.array([1,2,3])

In [ ]:
a+=2
a

array([5, 6, 7])

In [ ]:
a-2

array([3, 4, 5])

In [ ]:
a*2

array([10, 12, 14])

In [ ]:
a/2

array([2.5, 3. , 3.5])

In [ ]:
a

array([5, 6, 7])

In [ ]:
b = ([1,0,1])

In [ ]:
a+b

array([6, 6, 8])

In [ ]:
c = a+b

In [ ]:
c

array([6, 6, 8])

trigonometric functions on arrays

In [ ]:
np.cos(b)


array([0.54030231, 1.        , 0.54030231])

In [ ]:
np.sin(b)

array([0.84147098, 0.        , 0.84147098])

Linear Algebra

In [ ]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
b = np.full((3,4),2)
b

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [ ]:
c = np.matmul(a,b)
c

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [ ]:
c.shape

(2, 4)

In [ ]:
c = np.identity(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#Find the determinant
np.linalg.det(c)

np.float64(1.0)

In [ ]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

Statistics

In [ ]:
stats =  np.array([[1, 2, 3],[5, 4, 6],[7,8,9]])
stats

array([[1, 2, 3],
       [5, 4, 6],
       [7, 8, 9]])

In [ ]:
np.min(stats,axis=1)

array([1, 4, 7])

In [ ]:
np.max(stats)

np.int64(9)

In [ ]:
np.sum(stats,axis=0)

array([13, 14, 18])

Reorganizing Arrays

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
#If we wanna make it 8*1
after = before.reshape((8,1))
after

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [ ]:
after = before.reshape((4,2))
after

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
after = before.reshape((2,2,2))
after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])


In [ ]:
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
#Horizontal stack
h1 = np.ones((2,4))
h2 = np.ones((2,2))

In [ ]:
np.hstack((h1,h2))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

Miscellaneous---
Data loading from files

In [ ]:
filedata=np.genfromtxt('numm.txt',delimiter=',')
filedata.astype('int32')
filedata

array([[0.41613222, 0.6843993 , 0.44592951, 0.08761771, 0.31545657],
       [0.1072231 , 0.30796527, 0.09058428, 0.57658282, 0.29002335],
       [0.75287294, 0.57164703, 0.72559665, 0.96664146, 0.07118143],
       [0.01400818, 0.50849501, 0.92296925, 0.83059435, 0.21245619],
       [0.90075886, 0.69989046, 0.04035632, 0.47700649, 0.58819832],
       [0.26999025, 0.92059524, 0.68905442, 0.32892971, 0.26737111],
       [0.63076789, 0.10106135, 0.60549234, 0.24075298, 0.39074433],
       [0.63245573, 0.63278708, 0.80486273, 0.31136989, 0.13594601],
       [0.77696037, 0.48563923, 0.37190617, 0.01279756, 0.94273225],
       [0.7016171 , 0.85601664, 0.98297456, 0.53594972, 0.81137444],
       [0.60640229, 0.55643285, 0.88017316, 0.28606354, 0.7760591 ],
       [0.67533082, 0.04859786, 0.60134485, 0.01401429, 0.31796438],
       [0.96962133, 0.46774566, 0.1663821 , 0.6272208 , 0.58819351],
       [0.57123273, 0.24206374, 0.19320665, 0.36229344, 0.83459886],
       [0.51948275, 0.99425187, 0.

#Boolean Masking and advance indexing

In [ ]:
filedata>0.1

array([[ True,  True,  True, False,  True],
       [ True,  True, False,  True,  True],
       [ True,  True,  True,  True, False],
       [False,  True,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True, False,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True, False,  True, False,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True, False, False,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [ ]:
filedata=filedata[filedata<0.1]

You can index with a *list* in numpy

In [ ]:
filedata.reshape(5,2)

array([[0.08761771, 0.09058428],
       [0.07118143, 0.01400818],
       [0.04035632, 0.01279756],
       [0.04859786, 0.01401429],
       [0.07310615, 0.04077923]])

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,5]]

array([2, 3, 6])

In [ ]:
np.any(filedata>0.1)

np.False_

In [ ]:
np.any(filedata<0.01401)

np.True_

***QUIZ TIME***

In [ ]:
#We have an array
ar = np.array([])

In [25]:
m = np.arange(1,31).reshape(6,5)
print(m)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [27]:
#task 1 print 11,12,13,14

m[2:-2,:2]

array([[11, 12],
       [16, 17]])

In [31]:
#Print 2,8,14,20
m[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [43]:
#print last two values of first and last two rows
m[[0,4,5],-2:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [ ]:
""